import type { Metadata } from "next";
import { Cute_Font } from "next/font/google";
import "./globals.css";
import StyledComponentsRegistry from "@/lib/registry";

const cuteFont = Cute_Font({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="kr">
      <body className={cuteFont.className}>
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </body>
    </html>
  );
}
